### ISSUE TITLE
Replace `manual: True/False` with mode specific flags, e.g. `anonymized: True/False`, `normalized: True/False` and `error_labeled: True/False`.

### ISSUE THREAD

**Issue by cajosc** [spraakbanken/swell-editor#115]
For #116.

**Comment by arildm** [comment]
What is actually the purpose of this?

The purpose of the `manual` flag seems to be related to the automatic alignment of words.

> We first remove manually aligned words, align the rest of the text automatically (see Figure 3a), and then insert the manually aligned words again in their correct position (Figure 3b). Here the correct position is where they were removed from the respective texts. The editor indicates that this link is manually aligned by colouring it blue and (for the purposes of this article) making it dotted. These links interact differently with automatically aligned (grey) links.

I think the suggested states (anonymized, normalized, error-labeled) can be deduced by other elements in the graph data structure:

* anonymized if the edges has anonymization labels
* normalized if the target tokens are different from the source tokens (and it is not anonymized)
* error-labeled if the edges has normalization labels

These deductions rely on access to the label taxonomies, i.e. the ability to tell whether a label is an anonymization label or a correction label. But I don't think that's a problem.

**Comment by elenavolodina** [comment]
Here is an example of manual links from the "emergency" solution in November 2018, Stockholm: 

![skarmavbild 2019-01-14 kl 13 24 15](https://user-images.githubusercontent.com/31984909/51113025-fae6b100-1800-11e9-957d-5e9379275597.png)

The original text is rendered with grey background, word by word, and scrolling with "next mod" get you to the next token in the spaghetti, instead of to the next one where error-correction label needs to be added.

Wonder how this "next mod" would work for anonymized "manual" links?

**Comment by elenavolodina** [comment]
@cajosc 
Carl-Johan, could you please modify those texts that we anonymized in online SVALA during the November-meeting, so that manual links (=blue in the graph) can be removed from non-modified tokens?

**Comment by elenavolodina** [comment]
More details:
When I removed all anonymization tags, the manual link (=blue) was NOT removed in all cases, see the picture below. A stranger thing is about tripple "develooper of web" - I have not even a chance to group or orphan them:

![skarmavbild 2019-01-15 kl 14 03 48](https://user-images.githubusercontent.com/31984909/51182485-a27de500-18ce-11e9-9302-bf6a11c37cf7.png)

**Comment by arildm** [comment]
@cajosc I haven't pinned it down exactly, but I have gained some understanding of the invariant and alignment. Marking links as `manual` affects the alignment procedure, so I don't think it's unexpected that tinkering with the `manual` flag could violate the invariant.

I'll see if I can achieve a valid version of A3AT1.

**Comment by cajosc** [comment]
@elenavolodina A3AT1 has been modified. I haven't found any other essays with wrongly marked links.

**Comment by arildm** [comment]
> A stranger thing is about tripple "develooper of web" - I have not even a chance to group or orphan them

Now fixed in dev.

**Comment by arildm** [comment]
> When I removed all anonymization tags, the manual link (=blue) was NOT removed in all cases, see the picture below.

This is also fixed now.

**Comment by danr** [comment]
The purpose of the `manual` field is to tell the automatic aligner if the edge should be processed or if it has been manually linked by the user. So this is specific to each edge, not to an entire text. The procedure is explained in the clarin article.

When the flag is changed from true to false the aligner needs to be run again since the edge links could now be different. This is what has happened when the internal invariant error about the graph not automatically aligned is triggered.

I don't know what has happened in Elena's screenshot but it's ok to align more edges manually than what is strictly needed. Perhaps it should just be less visually intrusive.

**Comment by arildm** [comment]
I haven't really heard any arguments to add `anonymized`, `normalized` and `error_labeled`, so I'm closing this issue.
