### ISSUE TITLE
Activate anonymization mode during normalization

### ISSUE THREAD

**Issue by elenavolodina** [spraakbanken/swell-editor#90]
During normalization we would (maybe) need to correct anonymization or add/anonymize something. Then it should be possible to switch to that mode. E.g. we discover that during anonymization an assistant missed to anonymize "malmö" , so it should be fixed here and now.

**Comment by cajosc** [comment]
Do we need to rewrite history as well? Perhaps restrict access to history?

**Comment by cajosc** [comment]
Create issue automatically when anonymization tags are added in normalization mode in the portal?

> Do we need to rewrite history as well? Perhaps restrict access to history?

Rewrite manually for now.

**Comment by arildm** [comment]
Some progress on the frontend side.

Try it on the [dev site](https://spraakbanken.gu.se/swell/dev/#backend=aHR0cHM6Ly9zcHJhYWtiYW5rZW4uZ3Uuc2Uvc3dlbGwvZGV2LWJhY2tlbmQvYW5ub3RhdGlvbi9lc3NheS8=&essay=ST4SH&start_mode=norm):

1. click "switch to anonymization"
2. do some anonymization
3. click "switch to normalization"
4. try omitting running numbers; there should be a warning and not possible to re-enter normalization
5. try first doing some normalization, then anonymization. Note: normalization and word order changes will be lost, but error annotation labels should remain.

Still left to do:

* As @cajosc pointed out, the backend needs to be informed so that it can discard previous versions of the text, where the sensitive information was present

**Comment by cajosc** [comment]
Added a stub for support the the backend in spraakbanken/swell-portal@11b41d9.

**Comment by arildm** [comment]
Did some code cleanup and added a call to new `<essay_id>/report` endpoint, but haven't tested yet. This lives in the `reanonymize` branch.

**Comment by arildm** [comment]
This is now ready to be tested, e.g. at https://spraakbanken.gu.se/swell/dev/#backurl=aHR0cHM6Ly9zcHJhYWtiYW5rZW4uZ3Uuc2Uvc3dlbGwvZGV2LWJhY2tlbmQvdGFza3Mv&backend=aHR0cHM6Ly9zcHJhYWtiYW5rZW4uZ3Uuc2Uvc3dlbGwvZGV2LWJhY2tlbmQvdGFza3MvYW5ub3RhdGlvbi9hbm9ueW1pemF0aW9uLw==&essay=SV4MP&start_mode=norm

@elenavolodina
